apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-domain-operator
  namespace: openshift-operators
spec:
  replicas: 1
  selector:
    matchLabels:
      name: custom-domain-operator
  template:
    metadata:
      labels:
        name: custom-domain-operator
    spec:
      serviceAccountName: custom-domain-operator
      containers:
        - name: custom-domain-operator
          image: dustman9000/custom-domain-operator:0.0.3
          command:
          - custom-domain-operator
          args:
            - "--zap-level=debug"
            - "--zap-encoder=console"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "custom-domain-operator"
